version: '3.8'
services:
  rust-app:
    #build:
     # context: .
      #dockerfile: Dockerfile
    image: server
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    command: ["postgres", "-c", "listen_addresses=*"]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine-slim
    volumes:
      - ./html:/app/html
      - ./css:/app/css
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80
    depends_on:
      - rust-app

volumes:
  postgres-data:
